config/routes.rb
Rails.application.routes.draw do
  
  get '/artists', to: 'artists#index', as: 'artists'
  get 'artists/:id', to: 'artists#album', as: 'artist'
end

app/models/album.rb
class Album < ApplicationRecord
  has_many :songs
  belongs_to :artist
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
    has_many :albums
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :album
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  def index
    @artists = Artist.all
  end

  def album
    @albums = Album.where(artist_id: params[:id])
    @artist = Artist.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/views/artists/album.html.erb
<div class="container">
<div class="row">
    <div class="col-8">
        <h1><%=@artist.name%></h1>
        <h2>Albums (<%=@albums.count%>)</h2>

        <% @albums.each do |album|%>
            <div class="col-2">
                <div class="card" style="width: 18rem;">
                    <img class="card-img-top" src="<%= album.image_url %>" alt="Card image cap" height="160" width="160">
                    <div class="card-body">
                        <h5 class="card-title">
                            <%= album.name %>
                        </h5>
                        <p class="card-text"><%= album.released_at %></p>
                    </div>
                </div>
            </div>
            <%end%>
    </div>
</div>
</div>

app/views/artists/index.html.erb
<div class="container">
    <div class="row">
        <%@artists.each do |artist|%>
            <div class="col-3">
                <div class="card" style="width: 18rem;">
                    <img class="card-img-top" src="<%= artist.image_url %>" alt="Card image cap" height="260" width="260">
                    <div class="card-body">
                        <h5 class="card-title">
                            <%= artist.name %>
                        </h5>
                        <%= link_to 'See More', artist_path(artist)%>
                    </div>
                </div>
            </div>
            <%end%>     
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Spotify</title>
  <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

      <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <a type="button" href="<%=artists_url %>" class="btn btn-secondary">Artists</a>
  <button type="button" class="btn btn-success">My Music</button>
  <%= yield %>
</body>

</html>